// tinfo200:[2020-03-12-costarec-dykstra1] - creating course class with DatabaseGenerated attribute which specifies that 
// the values are not generated by the database. also declaring get-set properties
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}